server:
  port: 8000
spring:
  application:
    name: dubbo-demo-annotation-consumer
# dubbo 相关配置
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://192.168.8.15
    port: 2181
    timeout: 10000
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: top.simba1949.controller